In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
sys.path.append('../../')
from datasets import data as Local ## Local module to get dataframes

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import train_test_split

In [2]:
games_df, winners_df, cumulative_stats_df, games_details_df, teams_df, players_df, ranking_df = Local.get_all_dataset_dataframes('../../datasets/')

In [3]:
winners_df

16157    1
16156    1
16155    1
16154    1
16153    1
        ..
4        0
3        0
2        0
1        1
0        1
Name: HOME_TEAM_WINS, Length: 23520, dtype: int64

In [4]:
games_df

,GAME_DATE_EST,GAME_ID,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,PTS_home,FG_PCT_home,FT_PCT_home,FG3_PCT_home,AST_home,REB_home,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away
16157,2003-10-05,10300001,1610612762,1610612742,2003,90.0,0.457,0.735,0.143,23.0,41.0,85.0,0.447,0.500,0.250,20.0,38.0
16156,2003-10-06,10300002,1610612763,1610612749,2003,105.0,0.494,0.618,0.267,25.0,48.0,94.0,0.427,0.700,0.154,20.0,43.0
16155,2003-10-07,10300009,1610612758,1610612746,2003,101.0,0.467,0.871,0.444,19.0,39.0,82.0,0.368,0.609,0.364,13.0,50.0
16154,2003-10-07,10300005,1610612757,1610612745,2003,104.0,0.527,0.657,0.429,22.0,33.0,80.0,0.470,0.667,0.333,10.0,37.0
16153,2003-10-07,10300007,1610612748,1610612755,2003,86.0,0.352,0.647,0.222,15.0,55.0,79.0,0.329,0.897,0.143,7.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2020-12-18,12000040,1610612761,1610612748,2020,105.0,0.380,0.737,0.356,27.0,37.0,117.0,0.534,0.741,0.514,30.0,51.0
3,2020-12-18,12000039,1610612754,1610612755,2020,107.0,0.371,0.692,0.262,19.0,45.0,113.0,0.533,0.629,0.355,23.0,48.0
2,2020-12-19,12000049,1610612763,1610612737,2020,116.0,0.400,0.744,0.396,21.0,43.0,117.0,0.422,0.837,0.297,24.0,47.0
1,2020-12-19,12000048,1610612764,1610612765,2020,99.0,0.427,0.625,0.295,24.0,45.0,96.0,0.402,0.647,0.326,18.0,51.0
0,2020-12-19,12000047,1610612753,1610612766,2020,120.0,0.433,0.792,0.425,23.0,50.0,117.0,0.444,0.864,0.439,21.0,52.0

In [5]:
cumulative_stats_df

,DATE,GAME_ID,SEASON_TYPE,SEASON,GAMES_PLAYED_home,GAMES_PLAYED_away,APG_total_home,FG_PCT_total_home,FG3_PCT_total_home,FT_PCT_total_home,...,APG_total_away,FG_PCT_total_away,FG3_PCT_total_away,FT_PCT_total_away,PPG_total_away,RPG_total_away,TEAM_ID_away,TEAM_ID_home,W_PCT_away,W_PCT_home
0,2003-10-05,10300001,1,2003,1,1,23.000000,0.457000,0.143000,0.735000,...,20.0,0.44700,0.25000,0.50000,85.00,38.00,1610612742,1610612762,0.00,0.000
1,2003-10-06,10300002,1,2003,1,1,25.000000,0.494000,0.267000,0.618000,...,20.0,0.42700,0.15400,0.70000,94.00,43.00,1610612749,1610612763,0.00,0.000
2,2003-10-07,10300009,1,2003,1,1,19.000000,0.467000,0.444000,0.871000,...,13.0,0.36800,0.36400,0.60900,82.00,50.00,1610612746,1610612758,0.00,0.000
3,2003-10-07,10300005,1,2003,1,1,22.000000,0.527000,0.429000,0.657000,...,10.0,0.47000,0.33300,0.66700,80.00,37.00,1610612745,1610612757,0.00,0.000
4,2003-10-07,10300007,1,2003,1,1,15.000000,0.352000,0.222000,0.647000,...,7.0,0.32900,0.14300,0.89700,79.00,44.00,1610612755,1610612748,0.00,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23515,2020-12-18,12000040,1,2020,3,2,25.666667,0.422333,0.354000,0.706333,...,28.0,0.48050,0.39850,0.77950,104.50,43.00,1610612748,1610612761,0.50,0.667
23516,2020-12-18,12000039,1,2020,3,2,23.666667,0.415667,0.342667,0.643333,...,23.0,0.50200,0.29800,0.68950,110.50,45.00,1610612755,1610612754,1.00,0.000
23517,2020-12-19,12000049,1,2020,4,4,28.250000,0.450000,0.346000,0.714500,...,24.0,0.40000,0.32350,0.80150,112.75,53.75,1610612737,1610612763,0.50,0.750
23518,2020-12-19,12000048,1,2020,3,4,22.666667,0.419000,0.312667,0.678000,...,19.5,0.41050,0.33125,0.69650,94.00,44.00,1610612765,1610612764,0.50,0.333
23519,2020-12-19,12000047,1,2020,4,4,24.500000,0.441500,0.335250,0.766500,...,27.5,0.44275,0.38900,0.77925,112.25,46.75,1610612766,1610612753,0.25,0.500

In [6]:
cumulative_stats_copy_df = cumulative_stats_df.copy()
for key in ['DATE','GAME_ID','TEAM_ID_home','TEAM_ID_away','SEASON_TYPE','SEASON','GAMES_PLAYED_home','GAMES_PLAYED_away']:
    del cumulative_stats_copy_df[key]
# Only look at home teams
# cumulative_stats_copy_df = cumulative_stats_copy_df.loc[cumulative_stats_copy_df['AT_HOME']==True]
# del cumulative_stats_copy_df['AT_HOME']
cumulative_stats_copy_df

,APG_total_home,FG_PCT_total_home,FG3_PCT_total_home,FT_PCT_total_home,PPG_total_home,RPG_total_home,APG_total_away,FG_PCT_total_away,FG3_PCT_total_away,FT_PCT_total_away,PPG_total_away,RPG_total_away,W_PCT_away,W_PCT_home
0,23.000000,0.457000,0.143000,0.735000,90.000000,41.000000,20.0,0.44700,0.25000,0.50000,85.00,38.00,0.00,0.000
1,25.000000,0.494000,0.267000,0.618000,105.000000,48.000000,20.0,0.42700,0.15400,0.70000,94.00,43.00,0.00,0.000
2,19.000000,0.467000,0.444000,0.871000,101.000000,39.000000,13.0,0.36800,0.36400,0.60900,82.00,50.00,0.00,0.000
3,22.000000,0.527000,0.429000,0.657000,104.000000,33.000000,10.0,0.47000,0.33300,0.66700,80.00,37.00,0.00,0.000
4,15.000000,0.352000,0.222000,0.647000,86.000000,55.000000,7.0,0.32900,0.14300,0.89700,79.00,44.00,0.00,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23515,25.666667,0.422333,0.354000,0.706333,109.333333,40.000000,28.0,0.48050,0.39850,0.77950,104.50,43.00,0.50,0.667
23516,23.666667,0.415667,0.342667,0.643333,105.666667,38.666667,23.0,0.50200,0.29800,0.68950,110.50,45.00,1.00,0.000
23517,28.250000,0.450000,0.346000,0.714500,118.500000,50.250000,24.0,0.40000,0.32350,0.80150,112.75,53.75,0.50,0.750
23518,22.666667,0.419000,0.312667,0.678000,99.666667,44.666667,19.5,0.41050,0.33125,0.69650,94.00,44.00,0.50,0.333
23519,24.500000,0.441500,0.335250,0.766500,114.500000,51.000000,27.5,0.44275,0.38900,0.77925,112.25,46.75,0.25,0.500

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    cumulative_stats_copy_df,
    winners_df,
    train_size=0.8,
    random_state=0,
)

In [12]:
randomForest = RandomForestClassifier()

In [15]:
randomForest.fit(X_train, y_train)

RandomForestClassifier()

In [16]:
print('Random Forest accuracy (no optimizations): %.2f' % randomForest.score(X_test, y_test))

Random Forest accuracy (no pruning): 0.72

In [20]:
tuned_parameters_randomForest = [{'bootstrap': [True, False], 'max_depth': [1,2,3, 4,5], 'n_estimators': [10, 50, 100, 200, 500],'max_features': [1,2,3,4,5,6,7,8] }]
tuned_parameters_randomForest
scores_randomForest = ['precision', 'recall']

In [ ]:
for score in scores_randomForest:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(
        estimator = randomForest, param_grid = tuned_parameters_randomForest, scoring='%s_macro' % score
    )
    
    clf.fit(X_train, y_train)
    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()